#!/bin/zsh
zmodload zsh/mathfunc

case $BLOCK_BUTTON in
  3) xset dpms force off ;;  # right click, turn off
  4) xbacklight -inc 10 ;; # scroll up, increase
  5) xbacklight -dec 10 ;; # scroll down, decrease
esac

CUR="$(cat /sys/class/backlight/acpi_video0/actual_brightness)"
MAX="$(cat /cat /sys/class/backlight/acpi_video0/max_brightness)"

OUT=$(echo "$CUR / $MAX" | bc -l)

echo $((int($OUT*100)))%
