#!/bin/sh
#AccuWeather (r) RSS weather tool for conky
#
#USAGE: weather.sh UKXX0062
#
#(c) Michael Seiler 2007

METRIC=0 #Should be 0 or 1; 0 for F, 1 for C

if [ -z $1 ]; then
echo
echo "USAGE: weather.sh <locationcode>"
echo
exit 0;
fi

case $BLOCK_BUTTON in
  3) urxvt -e bash -c "forecast 15241; read -p 'press enter to exit: '"  ;;  
esac

curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=${METRIC}\&locCode\=$1 | perl -ne 'if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; print "$1"; }'
